name: Tests

on:
  pull_request:
    paths:
      - "src/**"
      - "tools/**"
      - "tests/**"
      - "requirements*.txt"
      - "pyproject.toml"
  push:
    branches: [main]

jobs:
  build-test:
    uses: ./.github/workflows/reusable_build_and_test_python_service.yml
    with:
      python_version: "3.12"
      requirements_file: "requirements-dev.txt"
      pytest_args: "-q"
